---
- name: Set locale
  block:

    - name: Debconf default locale
      debconf:
        name: locales
        question: locales/default_environment_locale
        value: "{{ locale_lang }}"
        vtype: select

    - name: Locale package present
      apt:
        pkg:
          - locales
        state: present

    - name: Locale present
      locale_gen:
        name: "{{ locale_lang }}"
        state: present

    - name: Check the environment
      command: systemctl show-environment
      register: locale_systemctlenv
      changed_when: false
      check_mode: false

    - name: Set a fact for the LANG
      set_fact:
        locale_lang_existing: "{{ line | regex_replace('^LANG=') }}"
      when: line is regex('^LANG=')
      loop: "{{ locale_systemctlenv.stdout_lines }}"
      loop_control:
        loop_var: line

    - name: Update LANG and locale
      block:

        - name: Set LANG
          command: "systemctl set-environment LANG={{ locale_lang }}"

        - name: Update locate
          command: update-locale "{{ locale_lang }}"

      when: ( locale_lang_existing != locale_lang )

  tags:
    - locale
...
