---
- name: Set locale
  block:

    - name: Debconf default locale
      ansible.builtin.debconf:
        name: locales
        question: locales/default_environment_locale
        value: "{{ locale_lang }}"
        vtype: select

    - name: Locale package present
      ansible.builtin.apt:
        pkg:
          - locales
        dpkg_options: force-confdef,force-confold
        install_recommends: true
        update_cache: true
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive
        LANG: "{{ locale_lang }}"
        LANGUAGE: "{{ locale_language }}"

    - name: Locale present
      community.general.locale_gen:
        name: "{{ locale_lang }}"
        state: present

    - name: Check the systemd environment
      ansible.builtin.command: systemctl show-environment
      changed_when: false
      check_mode: false
      register: locale_systemctlenv

    - name: Set a fact for the systemd environment
      ansible.builtin.set_fact:
        locale_environment: "{{ locale_systemctlenv.stdout | community.general.jc('ini') }}"

    - name: Set systemd LANG  # noqa yaml[comments] command-instead-of-module
      ansible.builtin.command: "systemctl set-environment LANG={{ locale_lang }}"
      when: ( locale_environment.LANG != locale_lang )

    - name: Set systemd LANGUAGE  # noqa yaml[comments] command-instead-of-module
      ansible.builtin.command: "systemctl set-environment LANGUAGE={{ locale_language }}"
      when: ( locale_environment.LANGUAGE != locale_language )

    - name: Slurp /etc/default/locale
      ansible.builtin.slurp:
        src: /etc/default/locale
      register: locale_default_existing_b64encoded
      changed_when: false
      check_mode: false

    - name: Set a fact for the default locale
      ansible.builtin.set_fact:
        locale_default_locale: "{{ locale_default_existing_b64encoded['content'] | b64decode | community.general.jc('ini') }}"

    - name: Update locale
      ansible.builtin.command: "update-locale LANG={{ locale_lang }} LANGUAGE={{ locale_language }}"
      when: >-
        ( locale_default_locale.LANG != locale_lang ) or
        ( locale_default_locale.LANGUAGE != locale_language )

  when: locale | bool
  tags:
    - locale
...
